### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/hive#7]
**@ me**:
- [x] Fix the reactivity of the app
- [x] Smaller dots
- [x] Add custom animation io
- [x] Center map
- [x] Smooth transitions by layering year markers
- [x] Make it buzz!
- [x] Add more demos
- [x] Add stories dropdown

@earowang:
- [x] Style the plots
- [x] Add violin plot
- [x] Colour scheme for points
- [x] Add hover/click events for leaflet
- [x] Add elevation data

@srkob1:
- [x] intro.js
- [x] Mention data cleaning and issues with temporal analysis
- [x] Continue working on slides
